library(data.table)
library(sp)
library(rgeos)
library(geosphere)
library(rgdal)

hawker_centres <- readOGR('/Users/luajiongwei/Downloads/hawker-centres/hawker-centres-kml.kml')
planning_area <- readOGR('/Users/luajiongwei/Downloads/master-plan-2014-planning-area-boundary-web/master-plan-2014-planning-area-boundary-web-shp/MP14_PLNG_AREA_WEB_PL.shp')
hc_coordinates <- as.data.table(hawker_centres@coords[,1:2])
coordinates(hc_coordinates) <- c('coords.x1', 'coords.x2')
proj4string(hc_coordinates) <- CRS("+proj=longlat +ellps=WGS84")
hc_coordinates <- spTransform(hc_coordinates, proj4string(planning_area))
hc_pln_area_mapping <- over(hc_coordinates, planning_area)
hc_pln_area_mapping <- as.data.table(hc_pln_area_mapping)
library(dplyr)
no_of_hc_by_pa <- hc_pln_area_mapping %>% group_by(PLN_AREA_N) %>% summarise(number_of_hc = n())
fwrite(no_of_hc_by_pa,'/Users/luajiongwei/Downloads/hc.csv')

bus_stops <- readOGR('/Users/luajiongwei/Downloads/BusStopLocation_Mar2018/BusStop.shp')
proj4string(bus_stops)
bus_stops$BUS_STOP_N
bus_stops_coords <-as.data.table(bus_stops@coords)
proj4string(bus_stops_coords) <-  proj4string(bus_stops)
bus_stops_coords <- spTransform(bus_stops_coords, CRS("+proj=longlat +ellps=WGS84"))
bus_stop_data <- data.table(as.data.table(bus_stops_coords), bus_stops$LOC_DESC, bus_stops$BUS_STOP_N) %>% rename(Bus_Stop_lon = coords.x1, Bus_Stop_Lat = coords.x2, Bus_Stop_Desc = V2, Bus_Stop_No = V3)
fwrite(bus_stop_data, '/Users/luajiongwei/Downloads/bus_stop.csv')
?spTransform